//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITM_Ventas.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int IdVenta { get; set; }
        public int IdCliente { get; set; }
        public int IdVehiculo { get; set; }
        public int IdAgencia { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public decimal Precio { get; set; }


        [JsonIgnore]
        public virtual Agencia Agencia { get; set; }

        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }

        [JsonIgnore]
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
